name: renemb
channels:
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.8.4
  - aiosignal=1.3.1
  - async-timeout=4.0.2
  - aws-c-auth=0.6.28
  - aws-c-cal=0.6.0
  - aws-c-common=0.8.23
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.0
  - aws-c-http=0.7.10
  - aws-c-io=0.13.27
  - aws-c-mqtt=0.8.13
  - aws-c-s3=0.3.11
  - aws-c-sdkutils=0.1.11
  - aws-checksums=0.1.16
  - aws-crt-cpp=0.20.2
  - aws-sdk-cpp=1.10.57
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.5.7
  - click=8.1.3
  - colorama=0.4.6
  - dataclasses=0.8
  - datasets=2.13.1
  - dill=0.3.6
  - frozenlist=1.3.3
  - gflags=2.2.2
  - glog=0.6.0
  - huggingface_hub=0.15.1
  - idna=3.4
  - importlib-metadata=6.7.0
  - importlib_metadata=6.7.0
  - keyutils=1.6.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - libabseil=20230125.3
  - libarrow=12.0.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.1.2
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libgomp=12.2.0
  - libgoogle-cloud=2.12.0
  - libgrpc=1.56.0
  - liblapack=3.9.0
  - libnghttp2=1.52.0
  - libnsl=2.0.0
  - libnuma=2.0.16
  - libopenblas=0.3.23
  - libprotobuf=4.23.3
  - libsqlite=3.40.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.1.0
  - libthrift=0.18.1
  - libutf8proc=2.8.0
  - libuuid=2.32.1
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - multidict=6.0.4
  - multiprocess=0.70.14
  - ncurses=6.3
  - openssl=3.1.1
  - orc=1.9.0
  - pip=23.0.1
  - pyarrow=12.0.1
  - pysocks=1.7.1
  - python=3.11.0
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python-xxhash=3.2.0
  - python_abi=3.11
  - pyyaml=6.0
  - rdma-core=28.9
  - re2=2023.03.02
  - s2n=1.3.46
  - sacremoses=master
  - safetensors=0.3.1
  - setuptools=67.6.0
  - six=1.16.0
  - snappy=1.1.10
  - tk=8.6.12
  - tokenizers=0.13.3
  - tqdm=4.65.0
  - transformers=4.30.2
  - typing_extensions=4.7.1
  - tzdata=2022g
  - ucx=1.14.1
  - wheel=0.40.0
  - xxhash=0.8.1
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.15.0
  - zstd=1.5.2
  - pip:
      - absl-py==1.4.0
      - accelerate==0.20.3
      - anyio==3.6.2
      - appdirs==1.4.4
      - arrow==1.2.3
      - attrs==22.2.0
      - beautifulsoup4==4.12.0
      - blessed==1.20.0
      - bounded-pool-executor==0.0.3
      - cachetools==5.3.0
      - certifi==2022.12.7
      - chardet==5.1.0
      - charset-normalizer==2.1.1
      - clevercsv==0.7.6
      - cmake==3.25.0
      - contourpy==1.0.7
      - croniter==1.3.8
      - cycler==0.11.0
      - dateutils==0.6.12
      - deepdiff==6.3.0
      - deepspeed==0.9.1
      - dnspython==2.3.0
      - docker-pycreds==0.4.0
      - email-validator==1.3.1
      - fastapi==0.88.0
      - filelock==3.9.0
      - fonttools==4.39.2
      - fsspec==2023.3.0
      - gitdb==4.0.10
      - gitpython==3.1.31
      - gnureadline==8.1.2
      - google-auth==2.16.3
      - google-auth-oauthlib==1.0.0
      - grpcio==1.51.3
      - h11==0.14.0
      - hjson==3.1.0
      - httpcore==0.16.3
      - httptools==0.5.0
      - httpx==0.23.3
      - inquirer==3.1.3
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - joblib==1.2.0
      - jsonnet==0.19.1
      - kiwisolver==1.4.4
      - lightning==2.0.0
      - lightning-bolts==0.6.0.post1
      - lightning-cloud==0.5.32
      - lightning-utilities==0.8.0
      - lit==15.0.7
      - lxml==4.9.2
      - markdown==3.4.3
      - markdown-it-py==2.2.0
      - markupsafe==2.1.2
      - matplotlib==3.7.1
      - mdurl==0.1.2
      - mpmath==1.2.1
      - networkx==3.0
      - ninja==1.11.1
      - nltk==3.8.1
      - numpy==1.24.3
      - oauthlib==3.2.2
      - openai==0.27.4
      - ordered-set==4.1.0
      - orjson==3.8.8
      - packaging==23.0
      - pandas==1.5.3
      - pathtools==0.1.2
      - pillow==9.3.0
      - pqdm==0.2.0
      - protobuf==3.20.3
      - psutil==5.9.4
      - py-cpuinfo==9.0.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pydantic==1.10.7
      - pygments==2.14.0
      - pyjwt==2.6.0
      - pyparsing==3.0.9
      - python-dotenv==1.0.0
      - python-editor==1.0.4
      - python-multipart==0.0.6
      - pytorch-lightning==2.0.0
      - pytz==2022.7.1
      - readchar==4.0.5
      - readline==6.2.4.1
      - regex==2023.3.22
      - requests==2.28.1
      - requests-oauthlib==1.3.1
      - rfc3986==1.5.0
      - rich==13.3.2
      - rolling==0.4.0
      - rsa==4.9
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - seaborn==0.12.2
      - sentry-sdk==1.17.0
      - setproctitle==1.3.2
      - smmap==5.0.0
      - sniffio==1.3.0
      - soupsieve==2.4
      - starlette==0.22.0
      - starsessions==1.3.0
      - sympy==1.11.1
      - tensorboard==2.12.2
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6
      - threadpoolctl==3.1.0
      - tiktoken==0.3.3
      - torch==2.0.0+cu118
      - torchaudio==2.0.1+cu118
      - torchdata==0.6.0
      - torchmetrics==0.11.4
      - torchtext==0.15.1
      - torchvision==0.15.1+cu118
      - traitlets==5.9.0
      - triton==2.0.0
      - typing-extensions==4.4.0
      - ujson==5.7.0
      - urllib3==1.26.13
      - uvicorn==0.21.1
      - uvloop==0.17.0
      - wandb==0.14.0
      - watchfiles==0.18.1
      - wcwidth==0.2.6
      - websocket-client==1.5.1
      - websockets==10.4
      - werkzeug==2.2.3
      - wget==3.2
      - yarl==1.8.2
